name:                 kanagawa
version:              1.0.0
visibility:           public
id:                   kanagawa-1.0.0-inplace
key:                  kanagawa-1.0.0-inplace
license:              MIT
copyright:            (C) Microsoft
maintainer:           adamsap@microsoft.com
author:               Adam Sapek, David Cox
homepage:             https://dl.acm.org/doi/10.1145/3656420
synopsis:             Kanagawa compiler frontend
description:
    Kanagawa is a High Level Synthesis (HLS) language for hardware design.

category:             Language
abi:                  inplace
exposed:              True
exposed-modules:
    Language.Kanagawa.Closure Language.Kanagawa.Constexpr
    Language.Kanagawa.Desugar Language.Kanagawa.Error
    Language.Kanagawa.Frontend Language.Kanagawa.Function
    Language.Kanagawa.Internal Language.Kanagawa.Mangle
    Language.Kanagawa.Parser Language.Kanagawa.Parser.IO
    Language.Kanagawa.Parser.Lexer Language.Kanagawa.Parser.Options
    Language.Kanagawa.Parser.Pattern
    Language.Kanagawa.Parser.SymbolTable
    Language.Kanagawa.Parser.Syntax
    Language.Kanagawa.Parser.Syntax.FixPattern
    Language.Kanagawa.Parser.Syntax.Pattern
    Language.Kanagawa.Parser.Syntax.TH Language.Kanagawa.PrettyPrint
    Language.Kanagawa.Recursion Language.Kanagawa.Symbols
    Language.Kanagawa.Template Language.Kanagawa.Type
    Language.Kanagawa.Type.Inference Language.Kanagawa.TypeCheck
    Language.Kanagawa.Warning

import-dirs:
    /home/runner/work/kanagawa/kanagawa/tools/sandcastle/dist-newstyle/build/x86_64-linux/ghc-9.6.7/kanagawa-1.0.0/build

library-dirs:
    /home/runner/work/kanagawa/kanagawa/tools/sandcastle/dist-newstyle/build/x86_64-linux/ghc-9.6.7/kanagawa-1.0.0/build

library-dirs-static:
    /home/runner/work/kanagawa/kanagawa/tools/sandcastle/dist-newstyle/build/x86_64-linux/ghc-9.6.7/kanagawa-1.0.0/build

dynamic-library-dirs:
    /home/runner/work/kanagawa/kanagawa/tools/sandcastle/dist-newstyle/build/x86_64-linux/ghc-9.6.7/kanagawa-1.0.0/build

data-dir:
    /home/runner/work/kanagawa/kanagawa/tools/sandcastle/../../compiler/.

hs-libraries:         HSkanagawa-1.0.0-inplace
depends:
    base-4.18.3.0 containers-0.6.7 directory-1.3.8.5
    edit-distance-0.2.2.1-b2a2b3ee1b106a123b9b9d41e2fe59608f2679da96a91053a93cb78f184094b7
    filepath-1.4.301.0
    hashable-1.5.1.0-061fa40cdb09caf8a652ca71cc2ef1505286758c49d8c3775594e6c29756c4ec
    integer-logarithms-1.0.5-493736c427196975c6a1f325ee4f6701e9f12f755162b4bb0c0f3f76497f4253
    megaparsec-9.8.1-e4c9ec223cfcaf681ac33558f7ff5585b95bf2d72222cecf36325381af752daf
    mtl-2.3.1
    parallel-3.3.0.0-b5fcbba04f7d775a5c56f566c7a95db5f498c8a4536cb825a0b3eb637f10726e
    parser-combinators-1.3.1-af2ca7cb7b1699625fc012b1ea362929f937d59141e4a82112ebfafede98b9bd
    prettyprinter-1.7.2-aad25a3c10c613670db1a3a00d4c2a3f6327824f3bda45298c5f8818e3dbe3ff
    splitmix-0.1.3.2-630cd9b66896126d57fa9cd0f56fac445d45e07bff08a64ad678dd1f99896650
    template-haskell-2.20.0.0 text-2.0.2
    unordered-containers-0.2.21-db9836cfb69ea8f5c81839d951e5ad10515afe7aeae33197949b8b33880822f2

ld-options:           "-Wl,-rpath,$ORIGIN"
haddock-interfaces:
    /home/runner/work/kanagawa/kanagawa/tools/sandcastle/dist-newstyle/build/x86_64-linux/ghc-9.6.7/kanagawa-1.0.0/doc/html/kanagawa/kanagawa.haddock

haddock-html:
    /home/runner/work/kanagawa/kanagawa/tools/sandcastle/dist-newstyle/build/x86_64-linux/ghc-9.6.7/kanagawa-1.0.0/doc/html/kanagawa
