name: Logic Tests (2/2)

# This test builds and runs some Kanagawa logic tests
# The logic tests are split into multiple workflows to reduce overall runtime
# See also logic-test-1.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    uses: ./.github/workflows/build-targets-template.yml
    with:
      build-targets: 'logic_tests_2'
      test-targets: 'run_logic_tests'
      cmake-build-type: 'RelWithDebInfo'
      runs-on: 'ubuntu-24.04'
      boost-platform-version: '24.04'

  # Temporarily disabled until the CMake configuration supports macOS
  # build-macos:
  #   uses: ./.github/workflows/build-targets-template.yml
  #   with:
  #     build-targets: 'logic_tests_2'
  #     test-targets: 'run_logic_tests'
  #     cmake-build-type: 'RelWithDebInfo'
  #     runs-on: 'macos-14'
  #     boost-platform-version: '14'
