name: Syntax Tests

# This test builds the main Kanagawa targets on Linux and macOS and
# then runs the syntax tests to validate the compiler front-end

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    uses: ./.github/workflows/build-targets-template.yml
    with:
      build-targets: 'syntax_tests'
      test-targets: 'run_syntax_tests'
      cmake-build-type: 'RelWithDebInfo'
      runs-on: 'ubuntu-24.04'
      boost-platform-version: '24.04'

  build-windows:
    uses: ./.github/workflows/build-targets-template.yml
    with:
      build-targets: 'syntax_tests'
      test-targets: 'run_syntax_tests'
      cmake-build-type: 'RelWithDebInfo'
      runs-on: 'windows-2022'
      boost-platform-version: '2022'

  # Temporarily disabled until the CMake configuration supports macOS
  # build-macos:
  #   uses: ./.github/workflows/build-targets-template.yml
  #   with:
  #     build-targets: 'syntax_tests'
  #     test-targets: 'run_syntax_tests'
  #     cmake-build-type: 'RelWithDebInfo'
  #     runs-on: 'macos-14'
  #     boost-platform-version: '14'
